/** Centralised TanStack Query keys so invalidation stays consistent across features. */
export const queryKeys = {
  session: ['session'] as const,
  me: {
    sessions: ['me', 'sessions'] as const,
    activity: (limit: number) => ['me', 'activity', limit] as const,
  },
  donor: {
    all: ['donor'] as const,
    profile: ['donor', 'profile'] as const,
    dashboard: ['donor', 'dashboard'] as const,
    organs: ['donor', 'organs'] as const,
    withdrawals: ['donor', 'withdrawals'] as const,
  },
  organs: {
    all: ['organs'] as const,
    availability: (params: object) => ['organs', 'availability', params] as const,
    summary: ['organs', 'summary'] as const,
    admin: (params: object) => ['organs', 'admin', params] as const,
  },
  hospitals: {
    all: ['hospitals'] as const,
    list: (params: object) => ['hospitals', 'list', params] as const,
    options: ['hospitals', 'options'] as const,
    cities: ['hospitals', 'cities'] as const,
  },
  admin: {
    all: ['admin'] as const,
    overview: ['admin', 'overview'] as const,
    donors: (params: object) => ['admin', 'donors', params] as const,
    donor: (id: string) => ['admin', 'donor', id] as const,
    withdrawals: (params: object) => ['admin', 'withdrawals', params] as const,
    withdrawalHistory: (id: string) => ['admin', 'withdrawal-history', id] as const,
  },
  organRequests: {
    all: ['organRequests'] as const,
    list: (params: object) => ['organRequests', 'list', params] as const,
    detail: (id: string) => ['organRequests', 'detail', id] as const,
    history: (id: string) => ['organRequests', 'history', id] as const,
  },
  analytics: {
    all: ['analytics'] as const,
    overview: ['analytics', 'overview'] as const,
    donors: (params: object) => ['analytics', 'donors', params] as const,
    organs: ['analytics', 'organs'] as const,
    hospitals: ['analytics', 'hospitals'] as const,
    withdrawals: (params: object) => ['analytics', 'withdrawals', params] as const,
    organRequests: (params: object) => ['analytics', 'organRequests', params] as const,
    trends: (params: object) => ['analytics', 'trends', params] as const,
  },
  recovery: {
    status: ['recovery', 'status'] as const,
  },
  public: {
    overview: ['public', 'overview'] as const,
    organs: ['public', 'organs'] as const,
    hospitals: ['public', 'hospitals'] as const,
    concentration: ['public', 'concentration'] as const,
    trends: ['public', 'trends'] as const,
    breaches: ['public', 'breaches'] as const,
    securityMatrix: ['public', 'security-matrix'] as const,
  },
  security: {
    all: ['security'] as const,
    overview: (params: object) => ['security', 'overview', params] as const,
    decisions: (params: object) => ['security', 'decisions', params] as const,
    denied: (params: object) => ['security', 'denied', params] as const,
    violations: (params: object) => ['security', 'violations', params] as const,
    trends: (params: object) => ['security', 'trends', params] as const,
    history: (params: object) => ['security', 'history', params] as const,
    aiEvents: (params: object) => ['security', 'ai-events', params] as const,
    aiBreakdown: (params: object) => ['security', 'ai-breakdown', params] as const,
  },
};
